language: python
python:
  - "3.4"
jobs:
  include:
    - stage: test
      script: nosetests
    - stage: deploy-git
      script: pip install git+https://github.com/StanIsAdmin/PyProt.git
    - stage: deploy-local
      script: pip install .
